### ISSUE TITLE
Property 'css' does not exist in the primitives

### ISSUE THREAD

**Issue by Bazai** [dstoyanoff/e-prim#21]
I tried to use this Box with the css prop from the example. Compiler is not happy.

```
      <Box
        onClick={console.log}
        p={4}
        shadow="xl"
        css={({ palette }) => ({
          outline: `${palette.warning.normal} solid 1px`,
        })}
      >
```
And the error is
> Property 'css' does not exist on type 'IntrinsicAttributes & MarginSystem & PaddingSystem & PositionProps & SizeProps & ColorProps & BorderProps & { ...; } & { ...; } & Omit<...>'

**Comment by dstoyanoff** [comment]
Hey, the CSS prop comes directly from Emotion. Here is a link from their docs on how to configure it - https://emotion.sh/docs/typescript

e-prim itself does not re-expose this property, but it is rather composed by emotion

**Comment by Bazai** [comment]
Thanks for the docs link. 
I see it works fine for your example project but not for my experimental one. It's clear that the bug is somewhere on my side. I'll try to figure it out. Closing the fail-start issue now 🎉 

Thank you so much for the link and best wishes for your project. I really like the concept and will be following you 👍

**Comment by Bazai** [comment]
The fix was just to add the string `"jsxImportSource" option to tsconfig.json:
```
{
  "compilerOptions": {
     ...
    "jsx": "react-jsx",
    "jsxImportSource": "@emotion/react"
  },
  ...
}

```

**Comment by dstoyanoff** [comment]
Glad you were able to solve your issue. 

I am open to feedback once you have some more time using the project. There are for sure more properties to be added in the system, but I rarely find myself needing them, so I've just added the most common ones for my style of coding and doing layouts
